repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.46.3
    hooks:
      - id: typos
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.21.2
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.7.1
    hooks:
      - id: tox-ini-fmt
