[tox]
requires =
    tox>=4.51
    tox-uv
env_list =
    3.14
    3.14t

[testenv]
runner = uv-venv-lock-runner
package = wheel
set_env =
    PYTHONDEVMODE = 1
commands =
    python -W error -m pytest {posargs:tests}
dependency_groups =
    dev
