[tox]
requires =
    tox>=4.2
env_list =
    py{314, 313, 312, 311, 314t, 313t}

[testenv]
runner = uv-venv-lock-runner
package = wheel
set_env =
    PYTHONDEVMODE = 1
commands =
    python -W error -m pytest {posargs:tests}
dependency_groups =
    dev
